'use client'

import { useMemo, useState } from 'react'
import type { CmsSection } from '@/lib/cms-sections'

export function CmsSectionRenderer({ section }: { section: CmsSection }) {
  const [query, setQuery] = useState('')
  const rows = useMemo(() => section.rows.filter((row) => Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase())), [section.rows, query])
  if (section.status === 'hidden') return null
  if (section.type === 'breadcrumb') return <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground">{section.content}</nav>
  return <section className="flex flex-col gap-3"><div><h2 className="font-serif text-2xl font-bold text-navy">{section.heading || section.title || 'Content section'}</h2>{section.intro && <p className="mt-2 text-muted-foreground">{section.intro}</p>}</div>{section.content && <p className="whitespace-pre-line leading-relaxed text-muted-foreground">{section.content}</p>}{['searchable_table', 'searchable_link_grid'].includes(section.type) && <input aria-label={`Search ${section.title || 'section'}`} className="rounded-lg border border-border px-3 py-2 text-sm" placeholder={section.searchPlaceholder} value={query} onChange={(event) => setQuery(event.target.value)} />}{section.rows.length > 0 && (section.type.includes('table') || section.type.endsWith('_table') || section.type === 'comparison_table' || section.type === 'documents_table' || section.type === 'fees_table' || section.type === 'process_table' || section.type === 'eligibility_table') ? <div className="overflow-x-auto rounded-lg border border-border"><table className="min-w-full border-collapse text-left text-sm"><thead><tr>{section.columns.map((column) => <th key={column.name} className="border-b border-border bg-surface px-3 py-2 font-bold">{column.name}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{section.columns.map((column) => <td key={column.name} className="border-b border-border px-3 py-2 align-top">{column.type === 'url' || column.type === 'anchor' ? <a className="text-brand hover:underline" href={row[column.name]}>{row[column.name]}</a> : row[column.name]}</td>)}</tr>)}</tbody></table></div> : section.rows.length > 0 && <div className="grid gap-3 sm:grid-cols-2">{rows.map((row, index) => <a key={index} href={row.URL || row.Url || '#'} className="rounded-lg border border-border bg-surface p-4"><strong className="text-navy">{row.Title || row.Anchor || row.Question || Object.values(row)[0]}</strong>{row.Description && <span className="mt-1 block text-sm text-muted-foreground">{row.Description}</span>}</a>)}</div>}</section>
}
