'use client'

import { FormEvent, useState } from 'react'
import { usePathname } from 'next/navigation'

const input = 'w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm outline-none focus:border-brand'

export function ContactForm() {
  const pathname = usePathname(); const [form, setForm] = useState({ name: '', mobile: '', email: '', service: '', message: '' }); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setNotice(''); const searchParams = new URLSearchParams(window.location.search); try { const response = await fetch('/api/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, landingPage: pathname, source: searchParams.get('utm_source') || '', medium: searchParams.get('utm_medium') || '', campaign: searchParams.get('utm_campaign') || '' }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || 'Submission failed.'); setForm({ name: '', mobile: '', email: '', service: '', message: '' }); setNotice('Thanks. Your enquiry has been received.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Submission failed.') } finally { setBusy(false) } }
  return <form onSubmit={submit} className="flex flex-col gap-4 rounded-xl border border-border bg-card p-6"><h2 className="font-serif text-2xl font-bold text-primary">Send an enquiry</h2><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-1.5 text-sm font-semibold text-navy">Name<input className={input} required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label className="flex flex-col gap-1.5 text-sm font-semibold text-navy">Mobile<input className={input} required value={form.mobile} onChange={(event) => setForm({ ...form, mobile: event.target.value })} /></label></div><label className="flex flex-col gap-1.5 text-sm font-semibold text-navy">Email<input className={input} type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="flex flex-col gap-1.5 text-sm font-semibold text-navy">Service<input className={input} value={form.service} onChange={(event) => setForm({ ...form, service: event.target.value })} /></label><label className="flex flex-col gap-1.5 text-sm font-semibold text-navy">Message<textarea className={`${input} resize-y`} rows={4} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></label>{notice && <p className="text-sm font-semibold text-navy">{notice}</p>}<button type="submit" disabled={busy} className="w-fit rounded-md bg-brand px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy ? 'Sending...' : 'Send enquiry'}</button></form>
}
