'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { categorySlug, inventory, inventoryCategories, publicServiceHref, type ServiceInventoryRecord } from '@/lib/service-inventory'
import { getPublicServiceGroups, type PublicService } from '@/lib/public-services'

function Card({ item, admin = false }: { item: ServiceInventoryRecord; admin?: boolean }) {
  const href = publicServiceHref(item)
  const matchLabel = item.matchType === 'exact_match' ? 'Exact match' : item.matchType === 'close_match' ? 'Close match' : item.matchType === 'related' ? 'Related' : item.matchType === 'existing_shubh' ? 'Existing service' : 'Unique reference'
  return <article className="flex h-full flex-col gap-3 rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-brand">{item.category}</p><h3 className="mt-1 font-serif text-lg font-bold text-navy">{item.canonicalTitle}</h3></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.status === 'existing_shubh' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{item.status === 'existing_shubh' ? 'Our service' : 'Planned'}</span></div><p className="text-sm text-muted-foreground">{item.subcategory}</p><div className="mt-auto flex items-center justify-between border-t border-border pt-3 text-xs"><span className="text-muted-foreground">{item.corpbizUrl && item.indiafilingsUrl ? 'Multiple references' : item.corpbizUrl || item.indiafilingsUrl ? 'Research reference' : 'Shubh'}</span>{admin ? <span className="font-semibold text-navy">{matchLabel}</span> : href ? <Link href={href} className="font-bold text-brand hover:underline">View service</Link> : <span className="font-semibold text-muted-foreground">Content pending</span>}</div></article>
}

export function ServiceInventoryDirectory({ admin = false, categoryFilter = 'All' }: { admin?: boolean; categoryFilter?: string }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [source, setSource] = useState('All')
  const filtered = useMemo(() => inventory.filter((item) => { const haystack = `${item.canonicalTitle} ${item.slug} ${item.subcategory}`.toLowerCase(); const sourceMatch = source === 'All' || source === 'Both' && item.corpbizUrl && item.indiafilingsUrl || source === 'Corpbiz' && item.corpbizUrl || source === 'IndiaFilings' && item.indiafilingsUrl || source === 'Unique' && (item.matchType === 'unique_corpbiz' || item.matchType === 'unique_indiafilings') || source === 'Our Services' && item.status === 'existing_shubh'; const categoryMatch = categoryFilter !== 'All' ? item.category === categoryFilter : category === 'All' || item.category === category; return haystack.includes(query.toLowerCase()) && categoryMatch && sourceMatch }), [query, category, source, categoryFilter])
  return <div className="mx-auto max-w-7xl px-4 py-12 md:px-6"><div className={`mb-8 grid gap-3 ${admin ? 'md:grid-cols-[1fr_220px_180px]' : 'md:grid-cols-[1fr_220px]'}`}><input aria-label="Search services" className="rounded-lg border border-border bg-background px-4 py-3 text-sm outline-none focus:border-brand" placeholder="Search services, e.g. trademark" value={query} onChange={(e) => setQuery(e.target.value)} /><select aria-label="Filter by category" className="rounded-lg border border-border bg-background px-4 py-3 text-sm" value={category} onChange={(e) => setCategory(e.target.value)} disabled={categoryFilter !== 'All'}><option>{categoryFilter === 'All' ? 'All' : categoryFilter}</option>{categoryFilter === 'All' && inventoryCategories.map((item) => <option key={item}>{item}</option>)}</select>{admin && <select aria-label="Filter by source" className="rounded-lg border border-border bg-background px-4 py-3 text-sm" value={source} onChange={(e) => setSource(e.target.value)}><option value="All">All references</option><option value="Our Services">Our services</option><option value="Corpbiz">Reference A</option><option value="IndiaFilings">Reference B</option><option value="Both">Both references</option><option value="Unique">Unique references</option></select>}</div><p className="mb-5 text-sm text-muted-foreground">Showing {filtered.length} of {categoryFilter === 'All' ? inventory.length : inventory.filter((item) => item.category === categoryFilter).length} unified services. Planned services are inventory records only and have no public SEO page yet.</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <Card key={item.id} item={item} admin={admin} />)}</div></div>
}

function PublicServiceCard({ service }: { service: PublicService }) { return <article className="flex h-full flex-col gap-3 rounded-xl border border-border bg-card p-5"><p className="text-xs font-bold uppercase tracking-wider text-brand">{service.category}</p><h2 className="font-serif text-lg font-bold text-navy">{service.name}</h2><p className="text-sm text-muted-foreground">{service.description}</p><Link href={service.href} className="mt-auto border-t border-border pt-3 text-sm font-bold text-brand hover:underline">View service</Link></article> }

export function CategoryDirectory({ slug }: { slug: string }) { const [groups, setGroups] = useState(() => getPublicServiceGroups()); const category = groups.find((group) => categorySlug(group.label) === slug)?.label ?? 'Services'; const services = groups.find((group) => group.label === category)?.items ?? []; useEffect(() => { const refresh = () => setGroups(getPublicServiceGroups()); window.addEventListener('scs-service-builder-updated', refresh); return () => window.removeEventListener('scs-service-builder-updated', refresh) }, []); return <><section className="bg-primary"><div className="mx-auto max-w-6xl px-4 py-14 md:px-6"><nav className="text-sm text-primary-foreground/70"><Link href="/">Home</Link> / <Link href="/services">Services</Link> / {category}</nav><h1 className="mt-6 max-w-3xl font-serif text-4xl font-bold text-primary-foreground">{category}</h1><p className="mt-4 max-w-2xl text-lg leading-relaxed text-primary-foreground/75">Explore active Shubh Consultancy services in {category.toLowerCase()}. Archived, hidden and unpublished services are not shown.</p></div></section><div className="mx-auto max-w-7xl px-4 py-12 md:px-6"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <PublicServiceCard key={service.slug} service={service} />)}</div></div></> }
