export type SectionType = 'rich_text' | 'heading_content' | 'bullet_list' | 'numbered_steps' | 'table' | 'searchable_table' | 'link_grid' | 'searchable_link_grid' | 'state_table' | 'city_table' | 'related_services' | 'popular_searches' | 'faq' | 'comparison_table' | 'documents_table' | 'fees_table' | 'process_table' | 'eligibility_table' | 'benefits' | 'cta' | 'image_content' | 'notice' | 'breadcrumb' | 'custom'
export type SectionStatus = 'published' | 'hidden'
export type TableColumn = { name: string; type: 'text' | 'number' | 'url' | 'anchor' | 'badge' }
export type SectionRow = Record<string, string>
export type SectionSource = 'manual' | 'ai_generated' | 'ai_improved' | 'manually_edited'
export type CmsSection = { id: string; pageId: string; title: string; type: SectionType; heading: string; intro: string; content: string; status: SectionStatus; order: number; searchPlaceholder: string; columns: TableColumn[]; rows: SectionRow[]; reusable: boolean; global: boolean; source?: SectionSource; revisionId?: string }
export type SectionAiContext = { service: string; pageType: string; state?: string; city?: string; primaryKeyword?: string; searchIntent?: string; targetAudience?: string; instruction: string; current: CmsSection; surrounding: CmsSection[] }
export type SectionRevision = { id: string; pageId: string; version: number; sections: CmsSection[]; createdAt: string }

export const sectionTypes: SectionType[] = ['rich_text', 'heading_content', 'bullet_list', 'numbered_steps', 'table', 'searchable_table', 'link_grid', 'searchable_link_grid', 'state_table', 'city_table', 'related_services', 'popular_searches', 'faq', 'comparison_table', 'documents_table', 'fees_table', 'process_table', 'eligibility_table', 'benefits', 'cta', 'image_content', 'notice', 'breadcrumb', 'custom']
const key = 'scs-cms-sections'
export function makeSection(pageId: string, type: SectionType = 'rich_text'): CmsSection { return { id: crypto.randomUUID(), pageId, title: '', type, heading: '', intro: '', content: '', status: 'published', order: 1, searchPlaceholder: 'Search this section', columns: [{ name: 'Title', type: 'text' }, { name: 'URL', type: 'url' }], rows: [], reusable: false, global: false } }
export function validateCmsSection(value: unknown, base: CmsSection): CmsSection | null { if (!value || typeof value !== 'object') return null; const candidate = value as Partial<CmsSection>; if (candidate.type !== base.type || !sectionTypes.includes(candidate.type) || typeof candidate.title !== 'string' || typeof candidate.heading !== 'string' || typeof candidate.intro !== 'string' || typeof candidate.content !== 'string' || !Array.isArray(candidate.columns) || !Array.isArray(candidate.rows)) return null; if (candidate.title.length > 180 || candidate.heading.length > 180 || candidate.intro.length > 2000 || candidate.content.length > 12000 || candidate.columns.length > 20 || candidate.rows.length > 100) return null; return { ...base, title: candidate.title, heading: candidate.heading, intro: candidate.intro, content: candidate.content, columns: candidate.columns as TableColumn[], rows: candidate.rows as SectionRow[], searchPlaceholder: typeof candidate.searchPlaceholder === 'string' ? candidate.searchPlaceholder : base.searchPlaceholder } }
export function getSections(pageId: string): CmsSection[] { if (typeof window === 'undefined') return []; try { return (JSON.parse(window.localStorage.getItem(key) || '[]') as CmsSection[]).filter((section) => section.pageId === pageId).sort((a, b) => a.order - b.order) } catch { return [] } }
const revisionKey = (pageId: string) => `scs-section-revisions-${pageId}`
export function getSectionRevisions(pageId: string): SectionRevision[] { if (typeof window === 'undefined') return []; try { return JSON.parse(window.localStorage.getItem(revisionKey(pageId)) || '[]') as SectionRevision[] } catch { return [] } }
export function saveSections(pageId: string, sections: CmsSection[]) { const all = (() => { try { return JSON.parse(window.localStorage.getItem(key) || '[]') as CmsSection[] } catch { return [] } })(); const previous = all.filter((section) => section.pageId === pageId).sort((a, b) => a.order - b.order); if (previous.length) { const revisions = getSectionRevisions(pageId); const revision: SectionRevision = { id: crypto.randomUUID(), pageId, version: revisions.length + 1, sections: structuredClone(previous), createdAt: new Date().toISOString() }; window.localStorage.setItem(revisionKey(pageId), JSON.stringify([...revisions, revision])) } window.localStorage.setItem(key, JSON.stringify([...all.filter((section) => section.pageId !== pageId), ...sections])) }
export function restoreSections(pageId: string, sections: CmsSection[]) { saveSections(pageId, sections.map((section, index) => ({ ...section, order: index + 1, source: 'manual' as const }))); return getSections(pageId) }
export function sectionLabel(type: SectionType) { return type.replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase()) }
