export type ContentPlanStatus = 'planned' | 'research_ready' | 'draft' | 'needs_review' | 'seo_ready' | 'approved' | 'published' | 'noindex' | 'rejected' | 'archived'
export type ContentPlanType = 'service' | 'service_state' | 'service_city' | 'service_state_city' | 'service_topic' | 'guide' | 'information' | 'comparison' | 'checklist' | 'faq_guide' | 'blog' | 'regulatory_guide' | 'state_guide' | 'city_guide'

export type ContentResearch = { source: string; url: string; topic: string; headings: string; questions: string; relatedServices: string }
export type ContentBrief = { primaryTopic: string; searchIntent: string; suggestedH1: string; suggestedH2s: string; suggestedH3s: string; questionsToAnswer: string; importantPoints: string; relatedServices: string; internalLinks: string; faqTopics: string; locationRequirements: string }
export type ContentPlan = {
  id: string; title: string; slug: string; pageType: ContentPlanType; category: string; subcategory: string; service: string; serviceId: string; state: string; stateId: string; city: string; cityId: string; topicId: string
  primaryKeyword: string; secondaryKeywords: string; searchIntent: string; targetAudience: string; status: ContentPlanStatus
  seoTitle: string; metaDescription: string; canonical: string; robotsIndex: boolean; robotsFollow: boolean; breadcrumbs: string; schema: string; sitemap: boolean; indexingStatus: string; imageAltText: string
  h1: string; introduction: string; mainContent: string; benefits: string; eligibility: string; documents: string; process: string; fees: string; importantInformation: string; conclusion: string; faqs: string
  research: ContentResearch; brief: ContentBrief; relatedServices: string; popularSearches: string; internalLinks: string; createdAt: string; updatedAt: string
}

const blankResearch = (): ContentResearch => ({ source: '', url: '', topic: '', headings: '', questions: '', relatedServices: '' })
const blankBrief = (): ContentBrief => ({ primaryTopic: '', searchIntent: '', suggestedH1: '', suggestedH2s: '', suggestedH3s: '', questionsToAnswer: '', importantPoints: '', relatedServices: '', internalLinks: '', faqTopics: '', locationRequirements: '' })
const now = () => new Date().toISOString()
export function makePlan(overrides: Partial<ContentPlan> = {}): ContentPlan { const timestamp = now(); return { id: crypto.randomUUID(), title: '', slug: '', pageType: 'service', category: '', subcategory: '', service: '', serviceId: '', state: '', stateId: '', city: '', cityId: '', topicId: '', primaryKeyword: '', secondaryKeywords: '', searchIntent: '', targetAudience: '', status: 'planned', seoTitle: '', metaDescription: '', canonical: '', robotsIndex: false, robotsFollow: true, breadcrumbs: '', schema: 'Auto', sitemap: false, indexingStatus: 'Not submitted', imageAltText: '', h1: '', introduction: '', mainContent: '', benefits: '', eligibility: '', documents: '', process: '', fees: '', importantInformation: '', conclusion: '', faqs: '', research: blankResearch(), brief: blankBrief(), relatedServices: '', popularSearches: '', internalLinks: '', createdAt: timestamp, updatedAt: timestamp, ...overrides } }

const testTitles = ['Trademark Registration in Delhi', 'Trademark Registration in Mumbai', 'Trademark Registration in Pune', 'Trademark Registration in Bangalore', 'Trademark Registration in Hyderabad', 'GST Registration in Delhi', 'GST Registration in Mumbai', 'FSSAI Registration in Pune', 'Company Registration in Bangalore', 'Income Tax Filing in Chandigarh']
export const testBatch: ContentPlan[] = testTitles.map((title) => { const city = title.split(' in ')[1]; const service = title.split(' in ')[0]; const slug = `${service}-${city}`.toLowerCase().replace(/[^a-z0-9]+/g, '-'); const state = city === 'Bangalore' ? 'Karnataka' : city === 'Mumbai' || city === 'Pune' ? 'Maharashtra' : city === 'Delhi' ? 'Delhi' : city === 'Hyderabad' ? 'Telangana' : 'Chandigarh'; return makePlan({ id: `plan-${slug}`, title, slug, pageType: 'service_city', category: service.startsWith('Trademark') ? 'Trademark & Intellectual Property' : service.startsWith('GST') ? 'GST & Tax' : service.startsWith('FSSAI') ? 'FSSAI & Food Licences' : service.startsWith('Company') ? 'Business Registration' : 'GST & Tax', subcategory: 'Location service page', service, serviceId: service.toLowerCase().replace(/[^a-z0-9]+/g, '-'), city, cityId: `city-${city.toLowerCase()}`, state, stateId: `state-${state.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`, topicId: '', primaryKeyword: `${service.toLowerCase()} in ${city.toLowerCase()}`, searchIntent: 'Local commercial', targetAudience: 'Business owners seeking local compliance support', brief: { ...blankBrief(), primaryTopic: `${service} requirements for businesses in ${city}`, searchIntent: 'Local commercial', suggestedH1: title, suggestedH2s: 'Eligibility\nDocuments\nProcess\nFees', questionsToAnswer: `Who needs ${service.toLowerCase()} in ${city}?`, locationRequirements: `Verify local requirements for ${city} before writing.` }, research: { ...blankResearch(), source: 'Internal research note', topic: `${service} local search coverage`, headings: 'Service overview; local process; documents', questions: `What should a customer in ${city} know?` } }) })

const companyRegistrationResearch = [
  ['startup', 'Company Registration in India', 'https://www.indiafilings.com/startup', 'national'],
  ['company-registration', 'Company Registration', 'https://www.indiafilings.com/company-registration', 'national'],
  ['register-company-india', 'Register Company in India', 'https://www.indiafilings.com/register-company-india', 'national'],
  ['delhi', 'Company Registration in Delhi', 'https://www.indiafilings.com/company-registration/delhi', 'state'],
  ['maharashtra', 'Company Registration in Maharashtra', 'https://www.indiafilings.com/company-registration/maharashtra', 'state'],
  ['west-bengal', 'Company Registration in West Bengal', 'https://www.indiafilings.com/company-registration/west-bengal', 'state'],
  ['karnataka', 'Company Registration in Karnataka', 'https://www.indiafilings.com/company-registration/karnataka', 'state'],
  ['tamil-nadu', 'Company Registration in Tamil Nadu', 'https://www.indiafilings.com/company-registration/tamil-nadu', 'state'],
  ['telangana', 'Company Registration in Telangana', 'https://www.indiafilings.com/company-registration/telangana', 'state'],
  ['gujarat', 'Company Registration in Gujarat', 'https://www.indiafilings.com/company-registration/gujarat', 'state'],
  ['kerala', 'Company Registration in Kerala', 'https://www.indiafilings.com/company-registration/kerala', 'state'],
  ['uttar-pradesh', 'Company Registration in Uttar Pradesh', 'https://www.indiafilings.com/company-registration/uttar-pradesh', 'state'],
  ['madhya-pradesh', 'Company Registration in Madhya Pradesh', 'https://www.indiafilings.com/company-registration/madhya-pradesh', 'state'],
  ['bihar', 'Company Registration in Bihar', 'https://www.indiafilings.com/company-registration/bihar', 'state'],
  ['uttarakhand', 'Company Registration in Uttarakhand', 'https://www.indiafilings.com/company-registration/uttarakhand', 'state'],
  ['tripura', 'Company Registration in Tripura', 'https://www.indiafilings.com/company-registration/tripura', 'state'],
  ['sikkim', 'Company Registration in Sikkim', 'https://www.indiafilings.com/company-registration/sikkim', 'state'],
  ['warangal', 'Company Registration in Warangal', 'https://www.indiafilings.com/company-registration/warangal', 'city'],
  ['visakhapatnam', 'Company Registration in Visakhapatnam', 'https://www.indiafilings.com/company-registration/visakhapatnam', 'city'],
  ['vijayawada', 'Company Registration in Vijayawada', 'https://www.indiafilings.com/company-registration/vijayawada', 'city'],
  ['vellore', 'Company Registration in Vellore', 'https://www.indiafilings.com/company-registration/vellore', 'city'],
  ['varanasi', 'Company Registration in Varanasi', 'https://www.indiafilings.com/company-registration/varanasi', 'city'],
  ['vadodara', 'Company Registration in Vadodara', 'https://www.indiafilings.com/company-registration/vadodara', 'city'],
  ['ujjain', 'Company Registration in Ujjain', 'https://www.indiafilings.com/company-registration/ujjain', 'city'],
  ['tiruvannamalai', 'Company Registration in Tiruvannamalai', 'https://www.indiafilings.com/company-registration/tiruvannamalai', 'city'],
  ['tirur', 'Company Registration in Tirur', 'https://www.indiafilings.com/company-registration/tirur', 'city'],
  ['tiruppur', 'Company Registration in Tiruppur', 'https://www.indiafilings.com/company-registration/tiruppur', 'city'],
  ['tirupati', 'Company Registration in Tirupati', 'https://www.indiafilings.com/company-registration/tirupati', 'city'],
  ['tirunelveli', 'Company Registration in Tirunelveli', 'https://www.indiafilings.com/company-registration/tirunelveli', 'city'],
  ['tiruchirappalli', 'Company Registration in Tiruchirappalli', 'https://www.indiafilings.com/company-registration/tiruchirappalli', 'city'],
  ['thrissur', 'Company Registration in Thrissur', 'https://www.indiafilings.com/company-registration/thrissur', 'city'],
  ['thiruvananthapuram', 'Company Registration in Thiruvananthapuram', 'https://www.indiafilings.com/company-registration/thiruvananthapuram', 'city'],
  ['surat', 'Company Registration in Surat', 'https://www.indiafilings.com/company-registration/surat', 'city'],
  ['srinagar', 'Company Registration in Srinagar', 'https://www.indiafilings.com/company-registration/srinagar', 'city'],
  ['solapur', 'Company Registration in Solapur', 'https://www.indiafilings.com/company-registration/solapur', 'city'],
  ['siliguri', 'Company Registration in Siliguri', 'https://www.indiafilings.com/company-registration/siliguri', 'city'],
  ['shimla', 'Company Registration in Shimla', 'https://www.indiafilings.com/company-registration/shimla', 'city'],
  ['sangli', 'Company Registration in Sangli', 'https://www.indiafilings.com/company-registration/sangli', 'city'],
  ['salem', 'Company Registration in Salem', 'https://www.indiafilings.com/company-registration/salem', 'city'],
  ['roorkee', 'Company Registration in Roorkee', 'https://www.indiafilings.com/company-registration/roorkee', 'city'],
] as const
export const companyRegistrationPlans: ContentPlan[] = companyRegistrationResearch.map(([slug, title, researchUrl, scope]) => { const location = scope === 'national' ? '' : title.split(' in ')[1]; const pageType = scope === 'national' ? 'service' : scope === 'state' ? 'service_state' : 'service_city'; return makePlan({ id: `research-company-${slug}`, title, slug: `services/company-registration${location ? `/${slug}` : ''}`, pageType, category: 'Business Registration', subcategory: scope === 'national' ? 'National service page' : `${scope} service page`, service: 'Company Registration', serviceId: 'company-registration', state: scope === 'state' ? location : '', stateId: scope === 'state' ? `state-${slug}` : '', city: scope === 'city' ? location : '', cityId: scope === 'city' ? `city-${slug}` : '', primaryKeyword: title.toLowerCase(), searchIntent: scope === 'national' ? 'Commercial and informational' : 'Local commercial', targetAudience: 'Founders and business owners evaluating an Indian company structure', canonical: `/services/company-registration${location ? `/${slug}` : ''}`, research: { ...blankResearch(), source: 'Private research reference', url: researchUrl, topic: `${title} search intent and coverage`, headings: 'Definition; structures; eligibility; documents; process; fees; compliance; FAQs', questions: 'What does a business owner need to know before choosing and registering a company?', relatedServices: 'LLP registration; OPC registration; GST registration; trademark registration' }, brief: { ...blankBrief(), primaryTopic: title, searchIntent: scope === 'national' ? 'Commercial and informational' : 'Local commercial', suggestedH1: title, suggestedH2s: 'Quick answer\nCompany structures\nEligibility\nDocuments\nRegistration process\nFees and timeline\nPost-registration compliance\nFAQs', suggestedH3s: 'Private limited company\nLLP\nOPC\nRegistered office\nGovernment filings', questionsToAnswer: 'Which structure fits the reader? What documents and steps are genuinely required?', importantPoints: 'Write original content using verified official sources; do not reuse research paragraphs or FAQs.', relatedServices: 'Link only to verified Shubh service routes.', internalLinks: '/services; /services/limited-liability-partnership-registration; /services/one-person-company-registration', locationRequirements: location ? `Verify the applicable jurisdiction and local context for ${location}; do not use name replacement alone.` : 'Explain nationwide MCA process and distinguish structure choices.' } }) })

export function getPlans(): ContentPlan[] { const seed = [...testBatch, ...companyRegistrationPlans]; if (typeof window === 'undefined') return seed; const raw = window.localStorage.getItem('scs-content-plans'); if (!raw) { window.localStorage.setItem('scs-content-plans', JSON.stringify(seed)); return seed } try { const saved = JSON.parse(raw) as ContentPlan[]; const known = new Set(saved.map((plan) => plan.id)); const merged = [...saved, ...seed.filter((plan) => !known.has(plan.id))]; if (merged.length !== saved.length) window.localStorage.setItem('scs-content-plans', JSON.stringify(merged)); return merged } catch { return seed } }
export function savePlans(plans: ContentPlan[]) { window.localStorage.setItem('scs-content-plans', JSON.stringify(plans)) }
export function planKey(plan: Pick<ContentPlan, 'pageType' | 'serviceId' | 'stateId' | 'cityId' | 'topicId'> & Partial<Pick<ContentPlan, 'service' | 'state' | 'city'>>) { return [plan.pageType, plan.serviceId || plan.service, plan.stateId || plan.state, plan.cityId || plan.city, plan.topicId].map((value) => (value ?? '').trim().toLowerCase()).join('|') }
export function isThinPlan(plan: ContentPlan) { const content = [plan.h1, plan.introduction, plan.mainContent, plan.benefits, plan.eligibility, plan.documents, plan.process, plan.fees, plan.importantInformation, plan.conclusion, plan.faqs].join(' ').trim(); return content.length < 300 || content.replace(new RegExp(plan.city || '__never__', 'gi'), '').trim().length < 240 }
export function planAudit(plan: ContentPlan, plans: ContentPlan[]) { const duplicateSlug = plans.some((item) => item.id !== plan.id && item.slug.trim() && item.slug.trim().toLowerCase() === plan.slug.trim().toLowerCase()); const key = planKey(plan); const duplicateKey = plans.some((item) => item.id !== plan.id && key !== '||||' && planKey(item) === key); const content = [plan.h1, plan.introduction, plan.mainContent, plan.benefits, plan.eligibility, plan.documents, plan.process, plan.fees, plan.importantInformation, plan.conclusion].join(' '); return [{ label: 'Primary keyword', ok: Boolean(plan.primaryKeyword), detail: plan.primaryKeyword || 'Missing' }, { label: 'H1 and SEO title', ok: Boolean(plan.h1 && plan.seoTitle), detail: `${plan.seoTitle.length} title characters` }, { label: 'Meta description', ok: Boolean(plan.metaDescription), detail: `${plan.metaDescription.length} description characters` }, { label: 'Canonical and robots', ok: Boolean(plan.canonical) && (!plan.sitemap || plan.robotsIndex), detail: plan.canonical || 'Missing canonical' }, { label: 'Content completeness', ok: content.length >= 500, detail: `${content.length} content characters` }, { label: 'Internal links and related services', ok: Boolean(plan.internalLinks && plan.relatedServices), detail: plan.internalLinks && plan.relatedServices ? 'Configured' : 'Add relationship data' }, { label: 'FAQ and media alt text', ok: Boolean(plan.faqs && plan.imageAltText), detail: plan.faqs && plan.imageAltText ? 'Configured' : 'Optional but recommended' }, { label: 'Duplicate protection', ok: !duplicateSlug && !duplicateKey, detail: duplicateSlug ? 'Duplicate slug' : duplicateKey ? 'Duplicate type/service/location' : 'No duplicate found' }, { label: 'Thin content protection', ok: !isThinPlan(plan), detail: isThinPlan(plan) ? 'THIN CONTENT WARNING' : 'Sufficient draft content' }].map((item) => ({ ...item, status: item.ok ? 'pass' : item.label.includes('Duplicate') && (duplicateSlug || duplicateKey) ? 'error' : 'warning' as 'pass' | 'warning' | 'error' })) }
export function planScore(plan: ContentPlan, plans: ContentPlan[]) { const audit = planAudit(plan, plans); return Math.round(audit.reduce((sum, item) => sum + (item.status === 'pass' ? 1 : 0), 0) / audit.length * 100) }
