export type ResearchMode = 'mock' | 'manual' | 'provider'
export type SearchIntent = 'informational' | 'commercial' | 'transactional' | 'navigational' | 'local'
export type Severity = 'critical' | 'high' | 'medium' | 'low'
export type TopicMap = { coreTopic: string; supportingTopics: string[]; questions: string[] }
export type EntityMap = { primary: string[]; regulatory: string[]; business: string[]; documents: string[]; process: string[]; locations: string[]; relatedServices: string[]; verificationRequired: string[] }
export type ContentGap = { topic: string; category: string; importance: Severity; reason: string }
export type CompetitorResearchInput = { url: string; title: string; headings: string; contentNotes: string; faqs: string; services: string; localInformation: string }
export type CompetitorInsight = { area: string; observation: string; recommendation: string; priority: Severity }
export type LocalSeoResearch = { targetCountry: string; targetState: string; targetCity: string; targetAreas: string[]; localKeywordPatterns: string[]; localIntent: string; localEntities: string[]; localTrustSignals: string[]; localContentOpportunities: string[]; locationSpecificFacts: string[]; locationVerificationRequired: string[] }
export type InternalLinkOpportunity = { sourcePage: string; targetPage: string; anchorSuggestion: string; reason: string; priority: Severity }
export type Risk = { type: string; pages: string[]; severity: Severity; recommendation: string }
export type ContentBlueprint = { recommendedTitle: string; recommendedMetaDescription: string; recommendedH1: string; h2s: string[]; h3s: string[]; topicsToCover: string[]; entitiesToMention: string[]; faqs: string[]; internalLinks: InternalLinkOpportunity[]; externalSources: string[]; eeatRequirements: string[]; localRequirements: string[]; conversionOpportunities: string[]; schemaRecommendations: string[]; aiSearchRecommendations: string[] }
export type AiSearchOptimization = { directAnswerTopics: string[]; answerBlockRecommendations: string[]; sourceAttribution: string[]; comparisonOpportunities: string[] }
export type SeoResearchRecord = { serviceSlug: string; serviceName: string; primaryKeyword: string; secondaryKeywords: string[]; longTailKeywords: string[]; questionKeywords: string[]; commercialKeywords: string[]; informationalKeywords: string[]; localKeywords: string[]; semanticKeywords: string[]; searchIntent: SearchIntent; secondaryIntent: SearchIntent[]; searchIntentExplanation: string; targetAudience: string[]; topicMap: TopicMap; entityMap: EntityMap; contentGaps: ContentGap[]; competitorInsights: CompetitorInsight[]; localSeo: LocalSeoResearch; internalLinkOpportunities: InternalLinkOpportunity[]; cannibalizationRisks: Risk[]; duplicateContentRisks: Risk[]; recommendedHeadings: string[]; recommendedFaqs: string[]; contentBlueprint: ContentBlueprint; eeatRequirements: string[]; aiSearchOptimization: AiSearchOptimization; researchNotes: string[]; confidence: 'low' | 'medium' | 'high'; researchMode: ResearchMode; researchedAt: string }
export type SeoResearchContext = { serviceSlug: string; serviceName: string; location?: string; primaryKeyword?: string; existingContent?: string; competitor?: CompetitorResearchInput }
const locationParts = (location = '') => { const parts = location.trim().split(',').map((part) => part.trim()).filter(Boolean); return { state: parts.length > 1 ? parts[parts.length - 2] : '', city: parts[parts.length - 1] || '' } }

export function createMockSeoResearch(context: SeoResearchContext): SeoResearchRecord {
  const location = locationParts(context.location); const service = context.serviceName; const keyword = context.primaryKeyword?.trim() || service; const localSuffix = location.city ? ` ${location.city}` : ''
  const questions = [`Who needs ${service}?`, `What documents are required for ${service}?`, `How does the ${service} process work?`, `How long does ${service} take?`, `What should applicants verify before applying?`]
  const supporting = ['Eligibility and categories', 'Required documents', 'Step-by-step process', 'Fees and timelines', 'Renewal and ongoing compliance', 'Common mistakes']
  const entities = [service, 'Applicant', 'Application process']; const localKeywords = location.city ? [`${keyword}${localSuffix}`, `${service} consultant${localSuffix}`, `${keyword} services${localSuffix}`] : []
  const internal = [{ sourcePage: service, targetPage: '/services', anchorSuggestion: 'business and compliance services', reason: 'Connect the service to the verified service directory.', priority: 'medium' as Severity }]
  const gaps = supporting.slice(0, 5).map((topic, index) => ({ topic, category: index === 1 ? 'documents' : 'topic', importance: index < 2 ? 'high' as Severity : 'medium' as Severity, reason: `A complete ${service} page should address this decision point clearly.` }))
  const localSeo: LocalSeoResearch = { targetCountry: 'India', targetState: location.state, targetCity: location.city, targetAreas: [], localKeywordPatterns: localKeywords, localIntent: location.city ? 'Users are looking for service support available in the selected location.' : 'No location was supplied; research is currently generic.', localEntities: location.city ? [location.city, location.state].filter(Boolean) : [], localTrustSignals: ['Verified contact details', 'Clear service availability statement', 'Location-specific support information only when verified'], localContentOpportunities: location.city ? ['Explain genuinely local service availability', 'Add location-specific FAQs after verification', 'Link to the relevant service and contact page'] : ['Add a location only when it changes the user value'], locationSpecificFacts: [], locationVerificationRequired: location.city ? ['Jurisdiction, office or process differences', 'Local availability and contact details'] : ['Target city and state before creating a location page'] }
  const blueprint: ContentBlueprint = { recommendedTitle: `${keyword} | Shubh Consultancy Services`, recommendedMetaDescription: `Understand ${keyword.toLowerCase()}, eligibility, documents, process and next steps with Shubh Consultancy Services.`, recommendedH1: keyword, h2s: ['What is this service?', 'Who needs it?', 'Eligibility and categories', 'Documents required', 'Application process', 'Fees and timeline', 'Common mistakes', 'Frequently asked questions'], h3s: supporting, topicsToCover: [service, ...supporting], entitiesToMention: entities, faqs: questions, internalLinks: internal, externalSources: ['Use the relevant official regulator or government portal after URL verification'], eeatRequirements: ['Show clear contact details', 'Explain document and process limits', 'Cite official sources when making regulatory claims', 'Mark facts requiring verification'], localRequirements: localSeo.localContentOpportunities, conversionOpportunities: ['Requirement review CTA', 'Contact option near the process and FAQ sections'], schemaRecommendations: ['Service', 'FAQPage only when visible FAQs match the page', 'BreadcrumbList'], aiSearchRecommendations: ['Lead sections with concise direct answers', 'Define entities before using abbreviations', 'Use question-led headings and ordered steps'] }
  const competitorInsights = context.competitor?.title || context.competitor?.headings ? [{ area: 'Manual competitor notes', observation: 'Notes were supplied by the admin; no website was fetched.', recommendation: 'Cover useful topics with original wording and verify every factual claim.', priority: 'medium' as Severity }] : []
  return { serviceSlug: context.serviceSlug, serviceName: service, primaryKeyword: keyword, secondaryKeywords: [`${keyword} process`, `${keyword} documents`, `${keyword} eligibility`], longTailKeywords: [`how to apply for ${keyword.toLowerCase()}`, `${keyword.toLowerCase()} documents and process`, `${keyword.toLowerCase()} for new businesses`], questionKeywords: questions, commercialKeywords: [`${service} consultant`, `${service} service`, `professional help for ${service}`], informationalKeywords: [`${service} process`, `${service} documents`, `${service} eligibility`], localKeywords, semanticKeywords: ['eligibility', 'documents', 'application', 'compliance', 'renewal', 'professional guidance'], searchIntent: location.city ? 'local' : 'commercial', secondaryIntent: ['commercial', 'transactional'], searchIntentExplanation: location.city ? 'The service wording signals commercial evaluation, while the supplied city adds a local intent layer. This is a qualitative mock classification, not search data.' : 'The service wording indicates users are evaluating help and next steps. This is a qualitative mock classification, not search data.', targetAudience: ['Business owners', 'Founders and applicants', 'People comparing filing support'], topicMap: { coreTopic: service, supportingTopics: supporting, questions }, entityMap: { primary: entities, regulatory: ['Relevant regulator or government portal (verify before publishing)'], business: ['Applicant business', 'Business owner'], documents: ['Identity proof', 'Business proof', 'Address proof'], process: ['Eligibility review', 'Document review', 'Application submission'], locations: location.city ? [location.city, location.state].filter(Boolean) : [], relatedServices: [], verificationRequired: ['Official requirements, fees, timelines and jurisdiction'] }, contentGaps: gaps, competitorInsights, localSeo, internalLinkOpportunities: internal, cannibalizationRisks: [], duplicateContentRisks: [], recommendedHeadings: blueprint.h2s, recommendedFaqs: questions, contentBlueprint: blueprint, eeatRequirements: blueprint.eeatRequirements, aiSearchOptimization: { directAnswerTopics: ['Eligibility', 'Documents', 'Process', 'Timeline'], answerBlockRecommendations: ['Answer each question in 40 to 60 words before adding detail.', 'Use ordered steps for the process.'], sourceAttribution: ['Add a verified official source for regulated claims.'], comparisonOpportunities: ['Compare applicable categories only after requirements are verified.'] }, researchNotes: ['Mock Research - Not Live SERP Data', 'No search volume, rankings, traffic, backlinks, CPC or competitor metrics are available.', 'Do not publish location or regulatory facts until manually verified.'], confidence: 'low', researchMode: 'mock', researchedAt: new Date().toISOString() }
}
export function researchStorageKey(serviceSlug: string) { return `scs-seo-research-${serviceSlug}` }
export function competitorFromText(value: string): CompetitorResearchInput { return { url: '', title: '', headings: '', contentNotes: value, faqs: '', services: '', localInformation: '' } }