import { contact, services } from '@/lib/site-data'
import type { SeoResearchRecord } from '@/lib/seo-research'

export type BuilderStatus = 'draft' | 'published' | 'archived'
export type BuilderItem = { id: string; title: string; description: string; icon: string; link: string; enabled: boolean; order: number }
export type BuilderDocument = BuilderItem & { required: 'required' | 'optional' }
export type BuilderProcessStep = BuilderItem
export type BuilderPricing = { id: string; planName: string; price: string; currency: string; description: string; governmentFee: string; professionalFee: string; cta: string; enabled: boolean; order: number }
export type BuilderFaq = { id: string; question: string; answer: string; enabled: boolean; order: number }
export type BuilderImage = { image: string; altText: string; title: string; caption: string }
export type BuilderSeo = { primaryKeyword: string; secondaryKeywords: string; seoTitle: string; metaDescription: string; canonicalUrl: string; robots: 'index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow'; ogTitle: string; ogDescription: string; ogImage: string }
export type ServiceBuilderRecord = {
  id: string; serviceSlug: string; serviceName: string; internalName: string; pageTitle: string; slug: string; shortDescription: string; status: BuilderStatus; visibility?: 'visible' | 'hidden'; displayOrder?: number; icon?: string
  locationGenerationEnabled?: boolean
  hero: { h1: string; description: string; image: BuilderImage; primaryCtaText: string; primaryCtaUrl: string; secondaryCtaText: string; secondaryCtaUrl: string }
  quickInfo: { startingPrice: string; processingTime: string; governmentFee: string; professionalFee: string; eligibility: string; documentsRequired: string; serviceType: string; enabled: Record<string, boolean> }
  about: { heading: string; description: string; image: BuilderImage }
  boxes: BuilderItem[]; benefits: BuilderItem[]; process: BuilderProcessStep[]; documents: BuilderDocument[]; pricing: BuilderPricing[]
  whyChooseUs: { heading: string; description: string; points: BuilderItem[]; image: BuilderImage; cta: string }
  faqs: BuilderFaq[]; cta: { heading: string; description: string; buttonText: string; buttonUrl: string; whatsappUrl: string; phoneUrl: string; backgroundImage: string }
  featuredImage: BuilderImage; seo: BuilderSeo; customBlocks: BuilderItem[]; updatedAt: string
}

const blankImage = (): BuilderImage => ({ image: '', altText: '', title: '', caption: '' })
const blankItem = (order: number): BuilderItem => ({ id: crypto.randomUUID(), title: '', description: '', icon: '', link: '', enabled: true, order })
const blankSeo = (): BuilderSeo => ({ primaryKeyword: '', secondaryKeywords: '', seoTitle: '', metaDescription: '', canonicalUrl: '', robots: 'index,follow', ogTitle: '', ogDescription: '', ogImage: '' })
export function createBuilderRecord(serviceSlug: string): ServiceBuilderRecord { const service = services.find((item) => item.slug === serviceSlug); return { id: `builder-${serviceSlug}`, serviceSlug, serviceName: service?.name ?? '', internalName: service?.name ?? '', pageTitle: service?.name ?? '', slug: serviceSlug, shortDescription: service?.summary ?? '', status: 'draft', hero: { h1: service?.name ?? '', description: service?.tagline ?? '', image: blankImage(), primaryCtaText: 'Talk to an Expert', primaryCtaUrl: contact.phonePrimaryHref, secondaryCtaText: 'WhatsApp', secondaryCtaUrl: contact.whatsappHref }, quickInfo: { startingPrice: service?.startingAt ?? '', processingTime: service?.timeline ?? '', governmentFee: '', professionalFee: '', eligibility: '', documentsRequired: '', serviceType: service?.category ?? '', enabled: { startingPrice: true, processingTime: true, governmentFee: false, professionalFee: false, eligibility: false, documentsRequired: false, serviceType: true } }, about: { heading: 'About this service', description: service?.intro.join('\n\n') ?? '', image: blankImage() }, boxes: [], benefits: [], process: service?.process.map((step, index) => ({ id: `process-${index}`, title: step.title, description: step.description, icon: '', link: '', enabled: true, order: index + 1 })) ?? [], documents: service?.documents.map((document, index) => ({ ...blankItem(index + 1), title: document, required: 'required' as const })) ?? [], pricing: [], whyChooseUs: { heading: 'Why choose Shubh Consultancy Services', description: 'Clear documentation support and practical guidance for your registration journey.', points: [], image: blankImage(), cta: 'Speak to our team' }, faqs: service?.faqs.map((faq, index) => ({ id: `faq-${index}`, question: faq.question, answer: faq.answer, enabled: true, order: index + 1 })) ?? [], cta: { heading: 'Ready to get started?', description: 'Talk to our team about the right next step for your business.', buttonText: 'Call us', buttonUrl: contact.phonePrimaryHref, whatsappUrl: contact.whatsappHref, phoneUrl: contact.phonePrimaryHref, backgroundImage: '' }, featuredImage: blankImage(), seo: { ...blankSeo(), primaryKeyword: service?.name.toLowerCase() ?? '', seoTitle: service?.name ?? '', metaDescription: service?.summary ?? '', canonicalUrl: `/services/${serviceSlug}` }, customBlocks: [], updatedAt: new Date().toISOString() } }

export const fssaiBuilderSeed = createBuilderRecord('fssai-food-licence')
fssaiBuilderSeed.status = 'published'
export const staticBuilderRecords: ServiceBuilderRecord[] = [fssaiBuilderSeed]
const storageKey = 'scs-service-builder'
let builderCache: ServiceBuilderRecord[] | null = null
export type MigrationReport = { imported: number; skipped: number; alreadyExists: number; errors: number }
export function getBuilderRecords(): ServiceBuilderRecord[] { if (typeof window === 'undefined') return [fssaiBuilderSeed]; if (builderCache) return builderCache; try { const saved = JSON.parse(window.localStorage.getItem(storageKey) || '[]') as ServiceBuilderRecord[]; builderCache = saved.length ? saved : [fssaiBuilderSeed]; if (!saved.length) window.localStorage.setItem(storageKey, JSON.stringify(builderCache)); return builderCache } catch { builderCache = [fssaiBuilderSeed]; return builderCache } }
export function saveBuilderRecords(records: ServiceBuilderRecord[]) { builderCache = records; window.localStorage.setItem(storageKey, JSON.stringify(records)); window.dispatchEvent(new Event('scs-service-builder-updated')) }
export function getServiceBuilderRecord(slug: string) { return staticBuilderRecords.find((record) => record.serviceSlug === slug && record.status === 'published') }
export function importExistingServices(records: ServiceBuilderRecord[]): { records: ServiceBuilderRecord[]; report: MigrationReport } { const existing = new Set(records.map((record) => record.serviceSlug)); const report: MigrationReport = { imported: 0, skipped: 0, alreadyExists: 0, errors: 0 }; const imported = services.reduce<ServiceBuilderRecord[]>((result, service) => { if (existing.has(service.slug)) { report.alreadyExists += 1; return result } try { result.push(createBuilderRecord(service.slug)); existing.add(service.slug); report.imported += 1 } catch { report.errors += 1 } return result }, []); const next = [...records, ...imported]; saveBuilderRecords(next); return { records: next, report } }
export function builderContent(record: ServiceBuilderRecord) { return [record.shortDescription, record.hero.description, record.about.description, ...record.boxes.map((item) => `${item.title} ${item.description}`), ...record.benefits.map((item) => `${item.title} ${item.description}`), ...record.process.map((item) => `${item.title} ${item.description}`), ...record.documents.map((item) => `${item.title} ${item.description}`), ...record.faqs.map((item) => `${item.question} ${item.answer}`)].join(' ') }
export type BuilderAudit = { label: string; status: 'pass' | 'warning' | 'error'; detail: string }
export function auditBuilder(record: ServiceBuilderRecord, research?: SeoResearchRecord): BuilderAudit[] { const content = builderContent(record); const keyword = record.seo.primaryKeyword.toLowerCase(); const hasImageWarning = [record.featuredImage, record.hero.image, record.about.image].some((image) => image.image && !image.altText); const researchAudits: BuilderAudit[] = research ? [{ label: 'Research intent alignment', status: research.searchIntent ? 'pass' : 'warning', detail: `${research.searchIntent} intent; review against the page.` }, { label: 'Research topic coverage', status: research.contentGaps.length ? 'warning' : 'pass', detail: research.contentGaps.length ? `${research.contentGaps.length} recommended topic gap(s).` : 'No mock gaps reported.' }, { label: 'Research entities and FAQs', status: research.entityMap.primary.length && research.recommendedFaqs.length ? 'pass' : 'warning', detail: 'Cover verified entities and visible FAQ answers.' }, { label: 'Research local SEO', status: research.localSeo.targetCity ? 'warning' : 'pass', detail: research.localSeo.targetCity ? 'Verify unique local value before publishing.' : 'No local target supplied.' }] : [] ; return [{ label: 'SEO title', status: record.seo.seoTitle ? 'pass' : 'error', detail: `${record.seo.seoTitle.length} characters` }, { label: 'Meta description', status: record.seo.metaDescription ? 'pass' : 'error', detail: `${record.seo.metaDescription.length} characters` }, { label: 'H1', status: record.hero.h1 ? 'pass' : 'error', detail: 'One predefined primary H1' }, { label: 'Focus keyword', status: keyword && record.hero.h1.toLowerCase().includes(keyword) ? 'pass' : keyword ? 'warning' : 'error', detail: keyword ? 'Review natural placement in the hero and introduction.' : 'Add a primary keyword.' }, { label: 'Content depth', status: content.length > 500 ? 'pass' : 'warning', detail: `${content.length} content characters` }, { label: 'FAQs', status: record.faqs.some((faq) => faq.enabled && faq.question && faq.answer) ? 'pass' : 'warning', detail: `${record.faqs.length} FAQ item(s)` }, { label: 'Internal links', status: record.boxes.some((item) => item.enabled && item.link) ? 'pass' : 'warning', detail: 'Use verified service URLs only.' }, { label: 'Images and alt text', status: hasImageWarning ? 'warning' : 'pass', detail: hasImageWarning ? 'An image needs alt text.' : 'No missing alt text detected.' }, { label: 'Canonical and robots', status: record.seo.canonicalUrl && record.seo.robots.startsWith('index') ? 'pass' : 'warning', detail: record.seo.canonicalUrl || 'Add canonical URL.' }, ...researchAudits] }
export function builderScore(record: ServiceBuilderRecord, research?: SeoResearchRecord) { const audit = auditBuilder(record, research); return Math.round(audit.filter((item) => item.status === 'pass').length / audit.length * 100) }
