import type { ServiceBuilderRecord } from '@/lib/service-builder'
import type { SeoResearchRecord } from '@/lib/seo-research'

export type AiContext = { service: string; pageType?: string; state?: string; city?: string; location?: string; primaryKeyword: string; secondaryKeywords: string; searchIntent?: string; targetAudience?: string; tone?: string; contentLength?: string; specialInstructions?: string; existingContent: string; competitorResearch?: string; research?: SeoResearchRecord }
export type AiAction = 'complete-page' | 'section' | 'rewrite' | 'seo' | 'faqs' | 'process' | 'benefits' | 'documents' | 'local-seo' | 'content-gap' | 'entities' | 'internal-links'
export function contextFromRecord(record: ServiceBuilderRecord): AiContext { return { service: record.serviceName, pageType: 'service', primaryKeyword: record.seo.primaryKeyword, secondaryKeywords: record.seo.secondaryKeywords, existingContent: [record.shortDescription, record.hero.description, record.about.description].join('\n'), targetAudience: 'Indian business owners', searchIntent: 'Commercial', tone: 'Professional and clear', contentLength: 'Standard' } }
const guardrails = 'Write original, factual Indian English. Preserve supplied facts. Do not invent approvals, guarantees, awards, reviews, statistics, credentials, prices, or legal requirements. Mark uncertain items for manual verification. Do not copy competitor wording.'
function researchContext(context: AiContext) { if (!context.research) return 'SEO research: Not available. Do not infer missing research.'; const research = context.research; return `SEO research: intent=${research.searchIntent}; secondary intent=${research.secondaryIntent.join(', ')}; topics=${research.topicMap.supportingTopics.join(', ')}; entities=${research.entityMap.primary.join(', ')}; gaps=${research.contentGaps.map((gap) => gap.topic).join(', ')}; local guidance=${research.localSeo.localContentOpportunities.join(', ')}; internal links=${research.internalLinkOpportunities.map((link) => `${link.targetPage} (${link.anchorSuggestion})`).join(', ')}; trust=${research.eeatRequirements.join(', ')}; answer-engine guidance=${research.aiSearchOptimization.answerBlockRecommendations.join(', ')}; blueprint headings=${research.contentBlueprint.h2s.join(', ')}.` }
export function buildPagePrompt(context: AiContext) { return `Create a structured, people-first service-page draft for ${context.service}. Page type: ${context.pageType || 'service'}. State: ${context.state || 'Not supplied'}. City: ${context.city || 'Not supplied'}. Focus keyword: ${context.primaryKeyword}. Secondary keywords: ${context.secondaryKeywords}. Search intent: ${context.searchIntent}. Audience: ${context.targetAudience}. Tone: ${context.tone || 'Professional and clear'}. Content length: ${context.contentLength || 'Standard'}. Special instructions: ${context.specialInstructions || 'None'}. Existing content: ${context.existingContent}. ${researchContext(context)} Use original wording, cover useful topics without padding, avoid cannibalization and keyword stuffing, and flag facts requiring verification. For uncertain regulatory or local claims, write VERIFY FACT in the relevant text. Return JSON only with optional hero, about, benefits, process, documents, faqs, localSeo and seo fields that map to the allowlisted ServiceBuilderRecord structure.` }
export function buildSectionPrompt(context: AiContext, section: string) { return `Create only the ${section} section for ${context.service}. Focus keyword: ${context.primaryKeyword}. ${guardrails} Do not modify unrelated sections.` }
export function buildFaqPrompt(context: AiContext) { return buildSectionPrompt(context, 'FAQ questions and answers') }
export function buildSeoPrompt(context: AiContext) { return `Suggest SEO title, meta description, slug, primary keyword, secondary keywords, canonical, robots, OG fields and image ALT recommendations for ${context.service}. ${researchContext(context)} ${guardrails} Keep metadata natural and aligned with intent.` }
export function buildLocalSeoPrompt(context: AiContext) { return `Create genuinely local, non-doorway-page guidance for ${context.service} in ${context.location || 'the selected location'}. ${guardrails} If no meaningful local distinction is known, say it requires manual verification.` }
export function buildContentGapPrompt(context: AiContext) { return `Review this ${context.service} content and list missing topics, entities, questions, trust signals and internal links: ${context.existingContent}. ${guardrails}` }
export function buildResearchPrompt(context: AiContext) { return `Research the SEO and content requirements for ${context.service}${context.location ? ` in ${context.location}` : ''}. Return qualitative keywords, intent, topics, entities, gaps, local guidance, internal links and a content blueprint. Never invent metrics or official facts. ${guardrails}` }
export function buildKeywordResearchPrompt(context: AiContext) { return `Build keyword groups for ${context.service}: primary, supporting, long-tail, questions, commercial, informational, local and semantic terms. Do not claim volume, difficulty or rankings. ${guardrails}` }
export function buildIntentPrompt(context: AiContext) { return `Classify search intent for ${context.service}${context.location ? ` in ${context.location}` : ''} with a primary intent, secondary intents and explanation. This is qualitative research only. ${guardrails}` }
export function buildTopicMapPrompt(context: AiContext) { return `Build a core topic, supporting topics and user questions for ${context.service}. ${guardrails}` }
export function buildEntityMapPrompt(context: AiContext) { return `Build an entity map for ${context.service}. Separate primary, regulatory, business, document, process and location entities. Mark uncertain facts for verification. ${guardrails}` }
export function buildGapAnalysisPrompt(context: AiContext) { return buildContentGapPrompt(context) }
export function buildCompetitorGapPrompt(context: AiContext) { return `Analyze only manually supplied competitor notes for ${context.service}. Recommend original topic, FAQ, entity, local, trust and conversion opportunities. Never scrape or copy wording. ${guardrails}` }
export function buildInternalLinkPrompt(context: AiContext) { return `Suggest internal links for ${context.service} using existing verified pages only. Identify orphan and irrelevant-link risks. ${guardrails}` }
export function buildCannibalizationPrompt(context: AiContext) { return `Compare service pages for keyword, topic, location and intent overlap for ${context.service}. Return warnings and recommendations only. ${guardrails}` }
export function buildContentBlueprintPrompt(context: AiContext) { return `Create a complete content blueprint for ${context.service}, including headings, entities, FAQs, links, sources, trust, local, schema and answer-engine recommendations. ${guardrails}` }
export function buildCustomBlocksPrompt(context: AiContext, action: string) { return `For ${context.service}, create a structured list of original ${action} recommendations. Return JSON only in the form {"items":[{"title":"...","description":"..."}]}. Do not invent regulatory, pricing, official, local or competitor facts; mark uncertain items with VERIFY FACT. ${guardrails}` }
export function buildContentGenerationPrompt(context: AiContext) { return buildPagePrompt(context) }
export function promptFor(action: AiAction, context: AiContext, section = 'the selected section') { if (action === 'complete-page') return buildPagePrompt(context); if (action === 'seo') return buildSeoPrompt(context); if (action === 'faqs') return buildFaqPrompt(context); if (action === 'local-seo') return buildLocalSeoPrompt(context); if (action === 'content-gap' || action === 'entities' || action === 'internal-links') return buildCustomBlocksPrompt(context, action); return buildSectionPrompt(context, action === 'section' ? section : action) }
