'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { getPages, type CmsPage } from '@/lib/page-cms'
import { getSectionRevisions, restoreSections, type SectionRevision } from '@/lib/cms-sections'

export default function RevisionsPage() {
  const [page, setPage] = useState<CmsPage | null>(null)
  const [revisions, setRevisions] = useState<SectionRevision[]>([])
  const [notice, setNotice] = useState('')
  useEffect(() => { const pageId = new URLSearchParams(window.location.search).get('page'); const current = getPages().find((item) => item.id === pageId) || getPages()[0] || null; setPage(current); if (current) setRevisions(getSectionRevisions(current.id).reverse()) }, [])
  const restore = (revision: SectionRevision) => { if (!page || !window.confirm(`Create a draft from section revision ${revision.version}?`)) return; restoreSections(page.id, revision.sections); setRevisions(getSectionRevisions(page.id).reverse()); setNotice(`Draft restored from section revision ${revision.version}.`); }
  if (!page) return <main className="p-8">No CMS page selected.</main>
  return <main className="min-h-screen bg-surface"><div className="mx-auto max-w-5xl px-4 py-10 md:px-6"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Admin / revisions</p><h1 className="mt-2 font-serif text-3xl font-bold text-navy">{page.title || 'Untitled page'}</h1><p className="mt-2 text-sm text-muted-foreground">Section snapshots are retained before each save. Restoring always remains a draft operation.</p></div><div className="flex gap-2"><Link href={`/admin/sections?page=${encodeURIComponent(page.id)}`} className="rounded-md border border-border px-4 py-2.5 text-sm font-bold text-navy">Back to sections</Link><Link href={`/preview?slug=${encodeURIComponent(page.slug)}`} target="_blank" className="rounded-md border border-brand px-4 py-2.5 text-sm font-bold text-brand">Preview</Link></div></div>{notice && <p className="mb-5 rounded-lg bg-emerald-100 p-3 text-sm font-bold text-emerald-700">{notice}</p>}{revisions.length === 0 ? <p className="rounded-xl border border-dashed border-border bg-background p-8 text-sm text-muted-foreground">No prior section revisions exist yet.</p> : <div className="flex flex-col gap-4">{revisions.map((revision) => <article key={revision.id} className="rounded-xl border border-border bg-background p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-serif text-xl font-bold text-navy">Section revision {revision.version}</h2><p className="text-xs text-muted-foreground">{new Date(revision.createdAt).toLocaleString()} · {revision.sections.length} section(s)</p></div><button type="button" onClick={() => restore(revision)} className="rounded-md bg-brand px-3 py-2 text-xs font-bold text-white">Create draft from this</button></div><details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-brand">Compare section snapshot</summary><div className="mt-3 grid gap-3 md:grid-cols-2">{revision.sections.map((section) => <div key={section.id} className="rounded-lg border border-border p-3"><p className="text-xs font-bold uppercase text-brand">{section.type} · {section.source || 'manual'}</p><p className="mt-1 font-semibold text-navy">{section.heading || section.title || 'Untitled section'}</p><p className="mt-2 whitespace-pre-line text-sm text-muted-foreground">{section.content || `${section.rows.length} structured row(s)`}</p></div>)}</div></details></article>)}</div>}</div></main>
}
