'use client'

import { useState } from 'react'
import { generateWithServerAi, getAiProvider, getAiProviderStatusFromServer, type AiProviderStatus, type AiSuggestion } from '@/lib/ai/provider'
import { contextFromRecord } from '@/lib/ai/prompts'
import { mockAiProvider } from '@/lib/ai/mock-provider'
import { getSections, saveSections, type CmsSection } from '@/lib/cms-sections'
import { getPages, saveCmsRevision, savePages, type CmsPage } from '@/lib/page-cms'
import { createBuilderRecord, type ServiceBuilderRecord } from '@/lib/service-builder'
import { useEffect } from 'react'

export function PageAiEditor({ page }: { page: CmsPage }) {
  const [instruction, setInstruction] = useState('Improve this page for search intent and readability.')
  const [proposal, setProposal] = useState<{ page: CmsPage; suggestion: AiSuggestion } | null>(null)
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')
  const [status, setStatus] = useState<AiProviderStatus>({ mode: 'mock', label: 'Mock', detail: 'Checking provider configuration.' })
  useEffect(() => { getAiProviderStatusFromServer().then(setStatus) }, [])
  const buildContext = () => { const record = createBuilderRecord(page.serviceId || page.slug); const context = contextFromRecord(record); return { ...context, service: page.title, pageType: page.pageType, state: page.stateId, city: page.cityId, primaryKeyword: page.primaryKeyword, secondaryKeywords: page.secondaryKeywords, searchIntent: page.searchIntent, targetAudience: page.targetAudience, existingContent: [page.h1, page.introduction, page.overview, page.mainContent, ...Object.values(page.serviceContent), ...Object.values(page.locationContent), ...page.faqs.map((faq) => `${faq.question}: ${faq.answer}`)].join('\n'), specialInstructions: instruction } }
  const toDraft = (suggestion: AiSuggestion) => { const next = structuredClone(page); const changes = suggestion.changes; if (changes.hero) { next.h1 = changes.hero.h1; next.introduction = changes.hero.description } if (changes.about) next.overview = changes.about.description; if (changes.benefits) next.serviceContent.benefits = changes.benefits.map((item) => `${item.title}: ${item.description}`).join('\n'); if (changes.process) next.serviceContent.process = changes.process.map((item) => `${item.title}: ${item.description}`).join('\n'); if (changes.documents) next.serviceContent.documentsRequired = changes.documents.map((item) => `${item.title}: ${item.description}`).join('\n'); if (changes.faqs) next.faqs = changes.faqs.map((item, index) => ({ id: item.id, question: item.question, answer: item.answer, status: 'draft', displayOrder: index + 1 })); if (instruction.toLowerCase().includes('seo') && changes.seo) { next.seoTitle = changes.seo.seoTitle; next.metaDescription = changes.seo.metaDescription; next.canonicalUrl = changes.seo.canonicalUrl; next.ogTitle = changes.seo.ogTitle; next.ogDescription = changes.seo.ogDescription } next.status = 'draft'; next.publishedAt = ''; next.updatedAt = new Date().toISOString(); return next }
  const generate = async () => { setLoading(true); setNotice(''); try { const context = buildContext(); const suggestion = status.mode === 'real' ? await generateWithServerAi('complete-page', context) : await mockAiProvider.generate('complete-page', context); setProposal({ page: toDraft(suggestion), suggestion }) } catch (error) { setNotice(error instanceof Error ? error.message : 'Page AI failed.') } finally { setLoading(false) } }
  const accept = () => { if (!proposal) return; const sections = getSections(page.id); saveCmsRevision(page, sections, 'ai-improved'); savePages(getPages().map((item) => item.id === page.id ? proposal.page : item)); saveSections(page.id, sections); setProposal(null); setNotice('AI draft saved. The current page remains unpublished until approval.') }
  return <section className="mb-6 rounded-xl border border-brand/20 bg-brand-tint p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">AI edit page</p><h2 className="font-serif text-xl font-bold text-navy">Create a proposed draft</h2><p className="mt-1 text-sm text-muted-foreground">Current page content is preserved. SEO fields change only when the instruction explicitly includes SEO.</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-brand">{status.label}</span></div><textarea aria-label="AI page instruction" className="mt-4 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm" rows={3} value={instruction} onChange={(event) => setInstruction(event.target.value)} /><button type="button" disabled={loading} onClick={generate} className="mt-3 rounded-md bg-brand px-4 py-2.5 text-sm font-bold text-white">{loading ? 'Generating…' : 'AI Edit Page'}</button>{notice && <p className="mt-3 text-sm font-semibold text-amber-800">{notice}</p>}{proposal && <div className="mt-5 rounded-lg border border-border bg-background p-4"><div className="grid gap-4 md:grid-cols-2"><div><p className="text-xs font-bold uppercase text-muted-foreground">Current page</p><p className="mt-2 font-semibold text-navy">{page.h1 || page.title}</p><p className="mt-1 text-sm text-muted-foreground">{page.introduction}</p></div><div><p className="text-xs font-bold uppercase text-brand">Proposed draft</p><p className="mt-2 font-semibold text-navy">{proposal.page.h1 || proposal.page.title}</p><p className="mt-1 text-sm text-muted-foreground">{proposal.page.introduction}</p></div></div><div className="mt-4 flex gap-2"><button type="button" onClick={accept} className="rounded-md bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Accept Draft</button><button type="button" onClick={() => setProposal(null)} className="rounded-md border border-border px-3 py-2 text-xs font-bold text-navy">Reject</button></div></div>}</section>
}

export function PageAiEditorStandalone() {
  const [page, setPage] = useState<CmsPage | null>(null)
  useEffect(() => { setPage(getPages()[0] || null) }, [])
  return page ? <PageAiEditor page={page} /> : null
}
