'use client'

import { useEffect, useState } from 'react'
import { getSeoResearchProvider } from '@/lib/ai/provider'
import { buildResearchPrompt } from '@/lib/ai/prompts'
import { competitorFromText, createMockSeoResearch, researchStorageKey, type CompetitorResearchInput, type SeoResearchContext, type SeoResearchRecord } from '@/lib/seo-research'
import type { ServiceBuilderRecord } from '@/lib/service-builder'

const input = 'w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/20'
const tabs = ['Overview', 'Keywords', 'Search Intent', 'Topic Map', 'Entities', 'Content Gaps', 'Competitors', 'Local SEO', 'Internal Links', 'Cannibalization', 'Blueprint'] as const
type Tab = typeof tabs[number]
const bullet = (items: string[]) => <ul className="space-y-2 text-sm text-muted-foreground">{items.map((item) => <li key={item} className="border-b border-border/70 pb-2 last:border-0">{item}</li>)}</ul>
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-border bg-background p-4 md:p-5"><h3 className="mb-3 font-serif text-lg font-bold text-navy">{title}</h3>{children}</section> }
function Chips({ items }: { items: string[] }) { return <div className="flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-full bg-brand-tint px-2.5 py-1 text-xs font-semibold text-navy">{item}</span>)}</div> }
function RowList({ items }: { items: { title: string; body: string }[] }) { return <div className="space-y-3">{items.map((item) => <div key={item.title} className="rounded-lg border border-border p-3"><p className="font-semibold text-navy">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.body}</p></div>)}</div> }

export function SeoResearchPanel({ record }: { record: ServiceBuilderRecord }) {
  const [location, setLocation] = useState(''); const [primaryKeyword, setPrimaryKeyword] = useState(record.seo.primaryKeyword); const [tab, setTab] = useState<Tab>('Overview'); const [research, setResearch] = useState<SeoResearchRecord | null>(null); const [draft, setDraft] = useState<SeoResearchRecord | null>(null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(''); const [competitorNotes, setCompetitorNotes] = useState('')
  useEffect(() => { try { const saved = window.localStorage.getItem(researchStorageKey(record.serviceSlug)); if (saved) setResearch(JSON.parse(saved) as SeoResearchRecord) } catch { setResearch(null) } }, [record.serviceSlug])
  const context = (): SeoResearchContext => ({ serviceSlug: record.serviceSlug, serviceName: record.serviceName, location, primaryKeyword, existingContent: [record.shortDescription, record.about.description].join('\n') })
  const runResearch = async () => { setLoading(true); setNotice(''); const result = await getSeoResearchProvider().researchService(context()); setDraft(result); setTab('Overview'); setLoading(false) }
  const accept = () => { if (!draft) return; window.localStorage.setItem(researchStorageKey(record.serviceSlug), JSON.stringify(draft)); window.dispatchEvent(new Event('scs-research-updated')); setResearch(draft); setDraft(null); setNotice('Research accepted and stored locally. Builder content was not changed.') }
  const discard = () => { setDraft(null); setNotice('Draft research discarded.') }
  const current = draft || research; const competitor = async () => { if (!competitorNotes.trim()) return; setLoading(true); const result = await getSeoResearchProvider().analyzeCompetitors({ ...context(), competitor: competitorFromText(competitorNotes) }, competitorFromText(competitorNotes)); setDraft(result); setTab('Competitors'); setLoading(false) }
  const renderTab = () => {
    if (!current) return <Panel title="Ready for research"><p className="text-sm text-muted-foreground">Run deterministic mock research to create a reviewable research brief. It uses no external data and never changes the service builder.</p></Panel>
    if (tab === 'Overview') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Search intent"><p className="text-2xl font-bold capitalize text-brand">{current.searchIntent}</p><p className="mt-2 text-sm text-muted-foreground">{current.searchIntentExplanation}</p><Chips items={current.secondaryIntent} /></Panel><Panel title="Research notes">{bullet(current.researchNotes)}</Panel><Panel title="Audience">{bullet(current.targetAudience)}</Panel><Panel title="Recommended headings">{bullet(current.recommendedHeadings)}</Panel></div>
    if (tab === 'Keywords') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Primary keyword"><p className="text-lg font-bold text-navy">{current.primaryKeyword}</p></Panel><Panel title="Secondary and semantic"><Chips items={[...current.secondaryKeywords, ...current.semanticKeywords]} /></Panel><Panel title="Long-tail queries">{bullet(current.longTailKeywords)}</Panel><Panel title="Questions">{bullet(current.questionKeywords)}</Panel><Panel title="Commercial and informational"><RowList items={[{ title: 'Commercial', body: current.commercialKeywords.join(' · ') }, { title: 'Informational', body: current.informationalKeywords.join(' · ') }, { title: 'Local', body: current.localKeywords.join(' · ') || 'Not available until a location is supplied.' }]} /></Panel></div>
    if (tab === 'Search Intent') return <Panel title="Intent classification"><RowList items={[{ title: `Primary: ${current.searchIntent}`, body: current.searchIntentExplanation }, { title: 'Secondary', body: current.secondaryIntent.join(' + ') }, { title: 'Data boundary', body: 'Qualitative mock classification only. No SERP or search-volume claims are made.' }]} /></Panel>
    if (tab === 'Topic Map') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Core topic"><p className="font-bold text-navy">{current.topicMap.coreTopic}</p></Panel><Panel title="Supporting topics">{bullet(current.topicMap.supportingTopics)}</Panel><Panel title="Questions">{bullet(current.topicMap.questions)}</Panel></div>
    if (tab === 'Entities') return <div className="grid gap-4 md:grid-cols-2">{Object.entries(current.entityMap).map(([key, values]) => <Panel key={key} title={key.replace(/([A-Z])/g, ' $1')}>{bullet(values as string[])}</Panel>)}</div>
    if (tab === 'Content Gaps') return <div className="space-y-3">{current.contentGaps.map((gap) => <div key={gap.topic} className="rounded-xl border border-border bg-background p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold text-navy">{gap.topic}</h3><span className="text-xs font-bold uppercase text-brand">{gap.importance}</span></div><p className="mt-1 text-sm text-muted-foreground">{gap.category}: {gap.reason}</p></div>)}</div>
    if (tab === 'Competitors') return <div className="space-y-4"><Panel title="Manual competitor research"><p className="mb-3 text-sm text-muted-foreground">Paste notes, headings or FAQs supplied by an admin. No URL is fetched.</p><textarea className={input} rows={5} value={competitorNotes} onChange={(event) => setCompetitorNotes(event.target.value)} placeholder="Competitor title, headings, FAQs and local notes" /><button type="button" onClick={competitor} className="mt-3 rounded-md bg-brand px-4 py-2.5 text-sm font-bold text-white">Analyze supplied notes</button></Panel><Panel title="Original recommendations">{current.competitorInsights.length ? <RowList items={current.competitorInsights.map((item) => ({ title: `${item.area} · ${item.priority}`, body: `${item.observation} ${item.recommendation}` }))} /> : <p className="text-sm text-muted-foreground">No manual competitor notes supplied.</p>}</Panel></div>
    if (tab === 'Local SEO') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Location"><RowList items={[{ title: 'Country', body: current.localSeo.targetCountry }, { title: 'State', body: current.localSeo.targetState || 'Not supplied' }, { title: 'City', body: current.localSeo.targetCity || 'Not supplied' }, { title: 'Intent', body: current.localSeo.localIntent }]} /></Panel><Panel title="Local opportunities">{bullet(current.localSeo.localContentOpportunities)}</Panel><Panel title="Verify before publishing">{bullet(current.localSeo.locationVerificationRequired)}</Panel><Panel title="Local keywords"><Chips items={current.localSeo.localKeywordPatterns.length ? current.localSeo.localKeywordPatterns : ['Not available - add a location']} /></Panel></div>
    if (tab === 'Internal Links') return <Panel title="Verified internal link opportunities"><RowList items={current.internalLinkOpportunities.map((item) => ({ title: `${item.sourcePage} -> ${item.targetPage} · ${item.priority}`, body: `${item.anchorSuggestion}: ${item.reason}` }))} /></Panel>
    if (tab === 'Cannibalization') return <Panel title="Cannibalization warnings"><p className="text-sm text-muted-foreground">{current.cannibalizationRisks.length ? 'Review these warnings before publishing.' : 'No page comparison was supplied. This mock run does not claim that cannibalization is absent.'}</p>{current.cannibalizationRisks.length > 0 && bullet(current.cannibalizationRisks.map((risk) => `${risk.severity}: ${risk.type} - ${risk.recommendation}`))}</Panel>
    return <div className="grid gap-4 md:grid-cols-2"><Panel title="Recommended title and H1"><RowList items={[{ title: 'Title', body: current.contentBlueprint.recommendedTitle }, { title: 'H1', body: current.contentBlueprint.recommendedH1 }, { title: 'Meta description', body: current.contentBlueprint.recommendedMetaDescription }]} /></Panel><Panel title="Headings">{bullet([...current.contentBlueprint.h2s, ...current.contentBlueprint.h3s])}</Panel><Panel title="Trust, local and conversion">{bullet([...current.contentBlueprint.eeatRequirements, ...current.contentBlueprint.localRequirements, ...current.contentBlueprint.conversionOpportunities])}</Panel><Panel title="Schema and answer engine">{bullet([...current.contentBlueprint.schemaRecommendations, ...current.contentBlueprint.aiSearchRecommendations])}</Panel><Panel title="FAQs">{bullet(current.contentBlueprint.faqs)}</Panel></div>
  }
  return <section className="mt-8 rounded-xl border border-brand/20 bg-brand-tint p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">SEO research · content intelligence</p><h2 className="mt-1 font-serif text-2xl font-bold text-navy">Research before generation</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Research is temporary until accepted. It does not publish, replace builder fields, scrape competitors or provide live metrics.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{current ? `${current.researchMode} research` : 'Not researched'}</span></div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-bold text-navy">Location<input className={`${input} mt-1`} value={location} onChange={(event) => setLocation(event.target.value)} placeholder="City, State (optional)" /></label><label className="text-sm font-bold text-navy">Primary keyword<input className={`${input} mt-1`} value={primaryKeyword} onChange={(event) => setPrimaryKeyword(event.target.value)} placeholder={record.serviceName} /></label><button type="button" onClick={runResearch} disabled={loading} className="self-end rounded-md bg-brand px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{loading ? 'Researching…' : 'Run SEO Research'}</button></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-muted-foreground">Mock Research - Not Live SERP Data</span>{current?.researchedAt && <span className="text-xs text-muted-foreground">Last researched {new Date(current.researchedAt).toLocaleString()}</span>}{draft && <><button type="button" onClick={accept} className="rounded-md bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Accept Research</button><button type="button" onClick={discard} className="rounded-md border border-red-300 px-3 py-2 text-xs font-bold text-red-700">Discard Research</button></>}{notice && <span className="text-xs font-semibold text-emerald-700">{notice}</span>}</div><div className="mt-5 flex gap-2 overflow-x-auto border-b border-border pb-2">{tabs.map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-md px-3 py-2 text-xs font-bold ${tab === item ? 'bg-navy text-white' : 'bg-background text-navy'}`}>{item}</button>)}</div><div className="mt-4">{renderTab()}</div><p className="mt-4 text-xs text-muted-foreground">Prompt preview: {buildResearchPrompt({ service: record.serviceName, location, primaryKeyword, secondaryKeywords: record.seo.secondaryKeywords, existingContent: record.shortDescription })}</p></section>
}