'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'

type FormRecord = { id: string; name: string; slug: string; description: string; active: boolean; fields: unknown }
const defaultFields = ['name', 'mobile', 'email', 'service', 'message']

export default function FormsPage() {
  const [forms, setForms] = useState<FormRecord[]>([]); const [name, setName] = useState('General Contact'); const [slug, setSlug] = useState('general-contact'); const [notice, setNotice] = useState('')
  useEffect(() => { fetch('/api/forms').then(async (response) => { const result = await response.json() as { items?: FormRecord[]; error?: string }; if (!response.ok) throw new Error(result.error || 'Could not load forms.'); setForms(result.items || []) }).catch((error) => setNotice(error instanceof Error ? error.message : 'Could not load forms.')) }, [])
  const create = async () => { const response = await fetch('/api/forms', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, slug, fields: defaultFields }) }); const result = await response.json() as { form?: FormRecord; error?: string }; if (!response.ok) { setNotice(result.error || 'Could not create form.'); return } setForms([result.form!, ...forms]); setNotice('Form created.') }
  return <main className="min-h-screen bg-surface"><div className="mx-auto max-w-5xl px-4 py-10 md:px-8"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow">Admin / forms</p><h1 className="mt-2 font-serif text-3xl font-bold text-navy">Contact form builder</h1><p className="mt-2 text-sm text-muted-foreground">Forms define validated lead fields. Document uploads are intentionally not enabled by default.</p></div><Link href="/admin/leads" className="rounded-md border border-brand px-4 py-2.5 text-sm font-bold text-brand">Leads</Link></div>{notice && <p className="mb-5 rounded-lg bg-amber-100 p-3 text-sm font-semibold text-amber-900">{notice}</p>}<section className="mb-6 rounded-xl border border-border bg-background p-5"><h2 className="font-serif text-xl font-bold text-navy">Create form</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input className="rounded-lg border border-border px-3 py-2.5 text-sm" value={name} onChange={(event) => setName(event.target.value)} placeholder="Form name" /><input className="rounded-lg border border-border px-3 py-2.5 text-sm" value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="Slug" /><button type="button" onClick={create} className="rounded-md bg-brand px-4 py-2.5 text-sm font-bold text-white">Create</button></div></section><div className="overflow-x-auto rounded-xl border border-border bg-background"><table className="w-full text-left text-sm"><thead className="bg-surface text-xs uppercase text-muted-foreground"><tr><th className="p-3">Name</th><th className="p-3">Slug</th><th className="p-3">Fields</th><th className="p-3">Status</th></tr></thead><tbody className="divide-y divide-border">{forms.map((form) => <tr key={form.id}><td className="p-3 font-semibold text-navy">{form.name}</td><td className="p-3 font-mono text-xs">{form.slug}</td><td className="p-3 text-xs">{Array.isArray(form.fields) ? form.fields.join(', ') : 'Configured'}</td><td className="p-3">{form.active ? 'Active' : 'Archived'}</td></tr>)}</tbody></table></div></div></main>
}
