'use client'

import { useEffect, useState } from 'react'
import { CmsPage, getPages } from '@/lib/page-cms'
import { getPlans, type ContentPlan } from '@/lib/content-plan'
import { getSections, type CmsSection } from '@/lib/cms-sections'
import { CmsSectionRenderer } from '@/components/cms-section-renderer'
import { getBuilderRecords } from '@/lib/service-builder'
import { ServiceBuilderRenderer } from '@/components/service-builder-renderer'

export default function CmsPreviewPage() {
  const [page, setPage] = useState<CmsPage | null>(null)
  const [plan, setPlan] = useState<ContentPlan | null>(null)
  const [sections, setSections] = useState<CmsSection[]>([])
  const [serviceRecord, setServiceRecord] = useState<ReturnType<typeof getBuilderRecords>[number] | null>(null)
  useEffect(() => { const params = new URLSearchParams(window.location.search); const slug = params.get('slug'); const planId = params.get('plan'); const serviceSlug = params.get('service'); const pageRecord = getPages().find((item) => item.slug === slug) ?? null; setPage(pageRecord); setPlan(getPlans().find((item) => item.id === planId) ?? null); setServiceRecord(getBuilderRecords().find((item) => item.serviceSlug === serviceSlug) ?? null); if (pageRecord) setSections(getSections(pageRecord.id)) }, [])
  if (serviceRecord) return <ServiceBuilderRenderer record={serviceRecord} />
  if (plan) return <main className="mx-auto max-w-4xl px-5 py-12 md:py-20"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-muted-foreground">{plan.breadcrumbs || ['Home', plan.category, plan.service, plan.state, plan.city, plan.title].filter(Boolean).join('  >  ')}</nav><p className="eyebrow">Planned preview · {plan.status}</p><h1 className="mt-3 font-serif text-4xl font-bold text-navy">{plan.h1 || plan.title}</h1><p className="mt-5 text-lg leading-relaxed text-muted-foreground">{plan.introduction || 'Write an original introduction in the Content tab.'}</p><div className="mt-10 flex flex-col gap-8">{[['Overview', plan.mainContent], ['Benefits', plan.benefits], ['Eligibility', plan.eligibility], ['Documents', plan.documents], ['Process', plan.process], ['Fees', plan.fees], ['Important information', plan.importantInformation], ['Conclusion', plan.conclusion]].filter(([, content]) => content).map(([heading, content]) => <section key={heading}><h2 className="font-serif text-2xl font-bold text-navy">{heading}</h2><p className="mt-3 whitespace-pre-line leading-relaxed text-muted-foreground">{content}</p></section>)}{plan.faqs && <section><h2 className="font-serif text-2xl font-bold text-navy">Frequently asked questions</h2><p className="mt-3 whitespace-pre-line leading-relaxed text-muted-foreground">{plan.faqs}</p></section>}</div></main>
  if (!page) return <main className="mx-auto max-w-3xl px-5 py-20"><h1 className="font-serif text-3xl font-bold text-navy">Preview unavailable</h1><p className="mt-3 text-muted-foreground">Choose a saved CMS page and open its preview link.</p></main>
  return <main className="mx-auto max-w-4xl px-5 py-12 md:py-20"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-muted-foreground">{(page.breadcrumbs.items.length ? page.breadcrumbs.items : ['Home', page.title]).join('  >  ')}</nav><p className="eyebrow">{page.categoryId || page.pageType}</p><h1 className="mt-3 font-serif text-4xl font-bold text-navy">{page.h1 || page.title}</h1>{page.introduction && <p className="mt-5 text-lg leading-relaxed text-muted-foreground">{page.introduction}</p>}<div className="mt-10 flex flex-col gap-8">{[page.overview, page.mainContent].filter(Boolean).map((content, index) => <section key={index}><h2 className="font-serif text-2xl font-bold text-navy">{index === 0 ? 'Overview' : 'Main content'}</h2><p className="mt-3 whitespace-pre-line leading-relaxed text-muted-foreground">{content}</p></section>)}{Object.entries(page.serviceContent).filter(([, content]) => content).map(([key, content]) => <section key={key}><h2 className="font-serif text-2xl font-bold capitalize text-navy">{key.replace(/[A-Z]/g, (letter) => ` ${letter}`)}</h2><p className="mt-3 whitespace-pre-line leading-relaxed text-muted-foreground">{content}</p></section>)}{page.blocks.filter((block) => block.status === 'active').sort((a, b) => a.displayOrder - b.displayOrder).map((block) => <section key={block.id}><h2 className="font-serif text-2xl font-bold text-navy">{block.title || 'Content section'}</h2><p className="mt-3 whitespace-pre-line leading-relaxed text-muted-foreground">{block.content}</p>{block.settings.links && <div className="mt-4 grid gap-3 sm:grid-cols-2">{block.settings.links.filter((link) => link.status === 'active').map((link) => <a key={link.id} href={link.url} className="rounded-lg border border-border bg-surface p-4 font-semibold text-brand hover:border-brand">{link.anchorText}<span className="mt-1 block text-sm font-normal text-muted-foreground">{link.description}</span></a>)}</div>}{block.settings.table && <div className="mt-4 overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead><tr>{block.settings.table.columns.map((column) => <th key={column} className="border border-border bg-surface p-3 font-bold">{column}</th>)}</tr></thead><tbody>{block.settings.table.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex} className="border border-border p-3">{cell}</td>)}</tr>)}</tbody></table></div>}</section>)}{page.faqs.length > 0 && <section><h2 className="font-serif text-2xl font-bold text-navy">Frequently asked questions</h2><div className="mt-4 divide-y divide-border rounded-xl border border-border">{page.faqs.filter((faq) => faq.status === 'active').map((faq) => <details key={faq.id} className="p-4"><summary className="cursor-pointer font-semibold text-navy">{faq.question}</summary><p className="mt-3 leading-relaxed text-muted-foreground">{faq.answer}</p></details>)}</div></section>}</div></main>
}
